# Generated by Django 4.1.1 on 2022-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="teste",
            field=models.BooleanField(default=True),
        ),
    ]
